services:
  member-web-app:
    build: .\Client\Member
    ports:
    - "4200:80"
  jcu-api:
    image: jesterapi:latest
    ports:
    - "5005:8080"
    environment:
    - BrassLoonLogClientId=${BrassLoonLogClientId}
    - BrassLoonLogClientSecret=${BrassLoonLogClientSecret}
    - IdentitificationCardContainerName=${IdentitificationCardContainerName}
    - EncryptionKeyVault=${EncryptionKeyVault}
    - CorsOrigins__0=${CorsOrigins__0}
    - JwkAddress=${JwkAddress}
    - GoogleIdAudiences__0=${GoogleIdAudiences__0}
    - GoogleIdAudiences__1=${GoogleIdAudiences__1}
    - BrassLoonConfigApiBaseAddress=${BrassLoonConfigApiBaseAddress}
    - BrassLoonLogApiBaseAddress=${BrassLoonLogApiBaseAddress}
    - BrassLoonLogRpcBaseAddress=${BrassLoonLogRpcBaseAddress}
    - BrassLoonAccountApiBaseAddress=${BrassLoonAccountApiBaseAddress}
    - BrassLoonWorkTaskApiBaseAddress=${BrassLoonWorkTaskApiBaseAddress}
    - BrassLoonAuthorizationApiBaseAddress=${BrassLoonAuthorizationApiBaseAddress}
    - AuthorizationDomainId=${AuthorizationDomainId}
    - ConfigDomainId=${ConfigDomainId}
    - LogDomainId=${LogDomainId}
    - WorkTaskDomainId=${WorkTaskDomainId}
  btch-loan-service-bus-processor: