CREATE PROCEDURE [ln].[UpdateLoanApplication]
	@id UNIQUEIDENTIFIER,
	@status SMALLINT,
	@applicationDate DATE,
	@borrowerName NVARCHAR(1024),
	@borrowerBirthDate DATE,
	@borrowerAddressId UNIQUEIDENTIFIER,
	@borrowerEmailAddressId UNIQUEIDENTIFIER,
	@borrowerPhoneId UNIQUEIDENTIFIER,
	@borrowerEmployerName NVARCHAR(1024),
	@borrowerEmploymentHireDate DATE,
	@borrowerIncome DECIMAL(11, 2),
	@coBorrowerName NVARCHAR(1024),
	@coBorrowerBirthDate DATE,
	@coBorrowerAddressId UNIQUEIDENTIFIER,
	@coBorrowerEmailAddressId UNIQUEIDENTIFIER,
	@coBorrowerPhoneId UNIQUEIDENTIFIER,
	@coBorrowerEmployerName NVARCHAR(1024),
	@coBorrowerEmploymentHireDate DATE,
	@coBorrowerIncome DECIMAL(11, 2),
	@amount DECIMAL(11, 2),
	@purpose NVARCHAR(2048),
	@mortgagePayment DECIMAL(7, 2),
	@rentPayment DECIMAL(7, 2),
	@timestamp DATETIME2(4) OUT
AS
BEGIN
	SET @timestamp = SYSUTCDATETIME();
	UPDATE [ln].[LoanApplication]
	SET [Status] = @status, 
	[ApplicationDate] = @applicationDate, 
	[BorrowerName] = @borrowerName, 
	[BorrowerBirthDate] = @borrowerBirthDate, 
	[BorrowerAddressId] = @borrowerAddressId, 
	[BorrowerEmailAddressId] = @borrowerEmailAddressId, 
	[BorrowerPhoneId] = @borrowerPhoneId, 
	[BorrowerEmployerName] = @borrowerEmployerName, 
	[BorrowerEmploymentHireDate] = @borrowerEmploymentHireDate, 
	[BorrowerIncome] = @borrowerIncome,
	[CoBorrowerName] = @coBorrowerName, 
	[CoBorrowerBirthDate] = @coBorrowerBirthDate, 
	[CoBorrowerAddressId] = @coBorrowerAddressId, 
	[CoBorrowerEmailAddressId] = @coBorrowerEmailAddressId, 
	[CoBorrowerPhoneId] = @coBorrowerPhoneId, 
	[CoBorrowerEmployerName] = @coBorrowerEmployerName, 
	[CoBorrowerEmploymentHireDate] = @coBorrowerEmploymentHireDate, 
	[CoBorrowerIncome] = @coBorrowerIncome,
	[Amount] = @amount, 
	[Purpose] = @purpose, 
	[MortgagePayment] = @mortgagePayment,
	[RentPayment] = @rentPayment,
	[UpdateTimestamp] = @timestamp
	WHERE [LoanApplicationId] = @id;
END
