CREATE TABLE [prt].[Party]
(
	[PartyId] UNIQUEIDENTIFIER NOT NULL,
	[Type] SMALLINT NOT NULL,
	[Name] NVARCHAR(1024) NOT NULL,
	[BeginDate] DATE NULL,
	[EndDate] DATE NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Party_CreateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_Party_UpdateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Party] PRIMARY KEY NONCLUSTERED ([PartyId])
)
