CREATE TABLE [ln].[Address]
(
	[AddressId] UNIQUEIDENTIFIER NOT NULL,
	[Hash] BINARY(64) NOT NULL,
	[Recipient] NVARCHAR(512) NOT NULL,
	[Attention] NVARCHAR(512) NOT NULL,
	[Delivery] NVARCHAR(512) NOT NULL,
	[Secondary] NVARCHAR(512) NOT NULL,
	[City] NVARCHAR(512) NOT NULL,
	[State] NCHAR(2) NOT NULL,
	[PostalCode] NVARCHAR(9),
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Address_CreateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Address] PRIMARY KEY NONCLUSTERED ([AddressId])
)

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Address_Hash] ON [ln].[Address] ([Hash])
