CREATE TABLE [ln].[Rating]
(
	[RatingId] UNIQUEIDENTIFIER NOT NULL,
	[Value] FLOAT NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Rating_CreateTimestamp] DEFAULT (SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Rating] PRIMARY KEY CLUSTERED ([RatingId])
)
