http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: "*"
    paths: 
    - /api/WeatherForecast
serviceEndpoints:
  api:
    url: http://localhost:5000/
  spa:
    url: http://localhost:4200/
policies:
  - cors
  - expression
  - log
  - jwt
  - proxy
  - rate-limit
pipelines:
  api:
    apiEndpoints: 
    - api
    policies:
    - rate-limit: &rateLimit
      - action:
          max: 600
          windowsMs: 60000
    - log:
      - action:
          message: ${req.method} ${req.hostname} ${req.originalUrl}
    - proxy:
      - action:
          serviceEndpoint: api
