http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  forms:
    host: "*"
    paths: /api/forms
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  jcuForms:
    url: "http://localhost:63264/"
policies:
  - cors
  - expression
  - log
  - jwt
  - proxy
  - rate-limit
  - body-parser
  - set-user-id
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  forms:
    apiEndpoints:
      - forms
    policies:
      - jwt:
        - action:
            secretOrPublicKeyFile: ./key/jestercreditunion-dvlp.pem
            checkCredentialExistence: false
      - rate-limit:
        - action:
            max: 600                      # max 600 request
            windowMs: 60000               # per 60 seconds
            rateLimitBy: "${req.user.id}" # EgContext.req.user.id                  
      - body-parser:
      - set-user-id:
      - proxy:
        - action:
            serviceEndpoint: jcuForms
