CREATE TABLE `LoanApplication` (
  `LoanApplicationId` binary(16) NOT NULL,
  `UserId` binary(16) DEFAULT NULL,
  `Status` smallint NOT NULL,
  `ApplicationDate` date NOT NULL,
  `BorrowerName` varchar(1024) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `BorrowerBirthDate` date NOT NULL,
  `BorrowerAddressId` binary(16) DEFAULT NULL,
  `BorrowerEmailAddressId` binary(16) DEFAULT NULL,
  `BorrowerPhoneId` binary(16) DEFAULT NULL,
  `BorrowerEmployerName` varchar(1024) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `BorrowerEmploymentHireDate` date DEFAULT NULL,
  `BorrowerIncome` decimal(11,2) DEFAULT NULL,
  `BorrowerIdentificationCardId` binary(16) DEFAULT NULL,
  `CoBorrowerName` varchar(1024) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CoBorrowerBirthDate` date DEFAULT NULL,
  `CoBorrowerAddressId` binary(16) DEFAULT NULL,
  `CoBorrowerEmailAddressId` binary(16) DEFAULT NULL,
  `CoBorrowerPhoneId` binary(16) DEFAULT NULL,
  `CoBorrowerEmployerName` varchar(1024) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CoBorrowerEmploymentHireDate` date DEFAULT NULL,
  `CoBorrowerIncome` decimal(11,2) DEFAULT NULL,
  `Amount` decimal(11,2) NOT NULL,
  `Purpose` varchar(2048) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `MortgagePayment` decimal(7,2) DEFAULT NULL,
  `RentPayment` decimal(7,2) DEFAULT NULL,
  `ClosedDate` date DEFAULT NULL,
  `CreateTimestamp` timestamp NOT NULL DEFAULT (utc_timestamp()),
  `UpdateTimestamp` timestamp NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`LoanApplicationId`),
  KEY `UserId` (`UserId`),
  KEY `BorrowerIdentificationCardId` (`BorrowerIdentificationCardId`),
  CONSTRAINT `FK_LoanApplication_To_BorrowerIdentificationCard` FOREIGN KEY (`BorrowerIdentificationCardId`) REFERENCES `IdentificationCard` (`IdentificationCardId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
